on:
  pull_request:
    types: [Open]
    branches:
      - develop
      - main

  handle-main-merge:
    if: github.event.pull_request.merged == false && github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.title, 'chore(main)')
    runs-on: ubuntu-latest
    needs: handle-develop-merge

    steps:
      - name: Approve PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ steps.create-pr.outputs.pr_url }} --approve
          
      - name: Extract tag from PR title
        id: extract
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          VERSION=$(echo "$TITLE" | grep -oP 'v\d+\.\d+\.\d+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag develop
        run: |
          git fetch origin develop
          git tag ${{ steps.extract.outputs.version }} origin/develop
          git push origin ${{ steps.extract.outputs.version }}

      - name: Tag main
        run: |
          git fetch origin main
          git tag -f ${{ steps.extract.outputs.version }} origin/main
          git push -f origin ${{ steps.extract.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          generate_release_notes: true