name: convert-and-release

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  handle-develop-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' && startsWith(github.event.pull_request.title, 'chore(develop)')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Reset develop to before merge
        run: |
          git fetch origin develop
          git checkout develop
          git push origin ${{ github.event.pull_request.merge_commit_sha }}^:develop --force
      
      - name: Create PR from develop to main
        id: create-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
          --base main \
          --head develop \
          --title "$(echo "${{ github.event.pull_request.title }}" | sed 's/chore(develop):/chore(main):/')" \
          --body "${{ github.event.pull_request.body }}"
          PR_URL=$(gh pr list --head develop --state open --json url -q '.[0].url')
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

